name = "I Know What We Are Going to Do Today"
author = "Spradley"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93de419b61a35355a40a2a8a727f42f3343be3456dd0ea73d0fe7cb12fe47a43"

[versions]
forge = "36.2.26"
minecraft = "1.16.5"
